### ISSUE TITLE
[BUG] quark-projects do not run in latest version

### ISSUE THREAD

**Issue by AddictArts** [Nishkalkashyap/Quark-electron#7]
### Issue Details

Showcase samples are not available with the latest version.

* **Quark Version:**
0.5.6

* **Operating System:**
Windows 10

* **Last Known Working Quark version:**
Unknown

### Expected Behavior
Open quark-projects/system-info/index.build.qrk runs and shows the showcase

### Actual Behavior
Open quark-projects/system-info/index.build.qrk runs and shows an error
Uncaught TypeError: quark.util.createVueWebComponent is not a function

### To Reproduce
Open the build file

### Additional Information
Note building failed at first. Then install systeminfo fixed that. Running still results in the same error.

**Comment by Nishkalkashyap** [comment]
Hey, thanks for opening your first issue.

The [Quark-projects](https://github.com/Nishkalkashyap/Quark-projects) repo needs an update. I wrote those projects long time ago, and since this project is still in development stage, a lot has changed.

If you're specifically looking for system-info project, I've updated it just now. You can check it out [here](https://github.com/Nishkalkashyap/quark-system-monitor) 

Also, a little secret. You can also download the project from [dash.quarkjs.io](https://dash.quarkjs.io/dashboard), which is an online app sharing platform for Quark apps. I'll probably make it public next month , until then feel free to check it out. I've already uploaded some sample apps there.

Cheers!

**Comment by AddictArts** [comment]
Thanks, I did check it out and created an account. You can close this if you want.
