### ISSUE TITLE
Generate EXE file.

### ISSUE THREAD

**Issue by k19812** [Nishkalkashyap/Quark-electron#9]
Hi,

Doesn't Quark generate an EXE installation (NSIS) file? (like electron)

Does it run only on Quark IDE?

Thank you.

**Comment by Nishkalkashyap** [comment]
No. Quark does not generates an exe or an NSIS file. This is intentional as you already have a framework for that and it's called [electron](https://electronjs.org).

For more information on why that is the case you can read my medium article [here](https://medium.com/hackernoon/announcing-quark-a-software-sketchbook-for-your-projects-2f53553415b)

**Comment by Nishkalkashyap** [comment]
Briefly explaining, Quark enables you to build native desktop app (like) sketches that have full capability of an electron application yet weighing only a few kilobytes instead of hundereds of megabytes. To share it with the world you can use [quark appstore](https://dash.quarkjs.io) _(currently under development)_ that takes care of all the things like auto-updates, release versioning e.t.c.

Quark is built to power small applications like todo apps, image resizers/converters, GUI client for cli's e.t.c

**Comment by k19812** [comment]
@Nishkalkashyap 
I got it.
Thank you :)
